" set options - NO spaces around =

" About neovim support :
" - cnvim - some default options are Changed : https://github.com/neovim/neovim/issues/2676
" - dnvim - Deleted options appear in red
" - envim - this is now enabled by default, therefore Extraneous

" better communication with OS
set clipboard=unnamedplus

" colors
" in neovim make sure to use export TERM=xterm-256colors instead | dnvim
set t_Co=256
let $NVIM_TUI_ENABLE_TRUE_COLOR=1
" beam cursor in insert mode
let $NVIM_TUI_ENABLE_CURSOR_SHAPE=1
syntax on
" colorscheme is set in plugins.vim

" display invisible chars
set list listchars=nbsp:•,eol:¬,tab:\¦\ ,trail:~,extends:▶,precedes:◀
" replace with fancy chars if declared (see after/syntax/javascript.vim)
set conceallevel=2
set lazyredraw

" crosshair
set cursorline cursorcolumn
" room to breath
set scrolloff=5

set hidden

" dirs
set directory=~/.vim/swap/
set backupdir=~/.vim/backup/
set undofile undodir=~/.vim/undo/

" tabs, default: T2 @see mappings.vim
set colorcolumn=80,120
set shiftwidth=2
set softtabstop=2
set tabstop=2
autocmd FileType javascript set formatprg=prettier\ --stdin

" don't truncate words
set linebreak
" only insert 1 space
set nojoinspaces

set statusline=%F\      "filename
set statusline+=[
set statusline+=%{strlen(&fenc)?&fenc:'none'}, "file encoding
set statusline+=%{&ff}, "file format (unix, windows)
set statusline+=%{getfsize(expand('%%:p'))}b "file size
set statusline+=]
set statusline+=%y      "filetype
set statusline+=%h      "help file flag
set statusline+=%m      "modified flag
set statusline+=%r      "read only flag
set statusline+=%=      "left/right separator
set statusline+=%c,     "cursor column
set statusline+=%l/%L   "cursor line/total lines
set statusline+=\ %P    "percent through file

" display current types keys in the bottom right corner
set showcmd

" used by gf to follow ES6 import - Ctrl-o to come back
set suffixesadd=.js,.jsx,.styl,.css

" Ctrl-p will look in dictionary if set spell is activated
set complete=.,w,b,u,t,i,kspell

set timeoutlen=1000 ttimeoutlen=0

if has('nvim')
	set inccommand=split
endif

" sources
if !has('nvim')
	source ~/.vim/compat.vim
endif
source ~/.vim/plugins.vim
source ~/.vim/mappings.vim
source ~/.vim/autocmds.vim
source ~/.vim/functions.vim

